
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX (open source Ansible Tower)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Install AWX
# --------------------------------------------------------------------------------------------------------------------------------------
# Create AWX

  
- name: AWX -                🚀 Create AWX Operator
  community.kubernetes.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/operator-install.yaml
  
- name: AWX -                🚀 Create AWX Instance
  community.kubernetes.k8s:
    state: present
    namespace: awx
    src: ./templates/awx/awx-deploy-cr.yml
