
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Train RobotShop Events
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Train RobotShop Events
# --------------------------------------------------------------------------------------------------------------------------------------
- name: RSEVENTS -           🚀 Check kafkacat executable
  shell: |
    if [ -x "$(command -v kafkacat)" ]; then
          echo "kafkacat"
    else
          if [ -x "$(command -v kcat)" ]; then
          export KAFKACAT_EXE=kcat
                echo "kcat"
          else
                echo "  ❗ ERROR: kafkacat is not installed."
                echo "  ❌ Aborting..."
                exit 1
          fi
    fi
  register: kafkacat_exe


- name: RSEVENTS -           🚀 Get EVENTS_TOPIC
  shell: |
    echo "alerts-noi-1000-1000" 
  register: EVENTS_TOPIC



- name: RSEVENTS -           🚀 Get KAFKA_PASSWORD
  shell: |
    echo "$(oc get secret token -n {{ WAIOPS_NAMESPACE }} --template=\{\{.data.password\}\}|base64 --decode)"
  register: KAFKA_PASSWORD


- name: RSEVENTS -           🚀 Get KAFKA_BROKER
  shell: |
    echo $(oc get routes strimzi-cluster-kafka-bootstrap -n {{ WAIOPS_NAMESPACE }}      -o=jsonpath='{.status.ingress[0].host}{"\n"}'):443
  register: KAFKA_BROKER


- name: RSEVENTS -           🚀 Get DATE_FORMAT
  shell: |
    echo "+%Y-%m-%dT%H:%M:%S"
  register: DATE_FORMAT



- name: RSEVENTS -           🚀 Get WORKING_DIR_EVENTS
  shell: |
    echo "./ansible/training/TRAINING_FILES/KAFKA/{{ APP_NAME }}/events"
  register: WORKING_DIR_EVENTS




- name: RSEVENTS -           🚀 Load Events
  shell: |
    export KAFKACAT_EXE={{ kafkacat_exe.stdout_lines[0] }}
    echo "KAFKACAT EXE:$KAFKACAT_EXE"
    echo {{ WORKING_DIR_EVENTS.stdout_lines[0] }}
    for actFile in $(ls -1 {{ WORKING_DIR_EVENTS.stdout_lines[0] }} | grep "json"); 
    do 

    #--------------------------------------------------------------------------------------------------------------------------------------------
    #  Prepare the Log Data
    #--------------------------------------------------------------------------------------------------------------------------------------------

          echo "***************************************************************************************************************************************************"
          echo "  🛠️  Preparing Data for file $actFile"
          echo "***************************************************************************************************************************************************"


          #--------------------------------------------------------------------------------------------------------------------------------------------
          echo  "Create file and structure in /tmp"
          #--------------------------------------------------------------------------------------------------------------------------------------------
          mkdir /tmp/training-events/
          rm /tmp/training-events/x*
          cp {{ WORKING_DIR_EVENTS.stdout_lines[0] }}/$actFile /tmp/training-events/
          cd /tmp/training-events/

          #--------------------------------------------------------------------------------------------------------------------------------------------
          echo "Split the files in 1500 line chunks for kafkacat"
          #--------------------------------------------------------------------------------------------------------------------------------------------
          echo "    🔨 Splitting"
          split -l 1500 $actFile
          export NUM_FILES=$(ls | wc -l)
          rm $actFile
          cd -
          echo "      ✅ OK"


          #--------------------------------------------------------------------------------------------------------------------------------------------
          echo  "Get the cert for kafkacat"
          #--------------------------------------------------------------------------------------------------------------------------------------------
          oc project {{ WAIOPS_NAMESPACE }}

          echo "***************************************************************************************************************************************************"
          echo "🥇 Getting Certs"
          echo "***************************************************************************************************************************************************"
          oc extract secret/strimzi-cluster-cluster-ca-cert -n {{ WAIOPS_NAMESPACE }} --keys=ca.crt
          echo "      ✅ OK"
          echo "***************************************************************************************************************************************************"

          echo $("pwd")
          echo "***************************************************************************************************************************************************"
          echo $("ls")
          echo "***************************************************************************************************************************************************"
          echo $("ls /tmp/training-events/")

          #--------------------------------------------------------------------------------------------------------------------------------------------
          #  Inject the Events
          #--------------------------------------------------------------------------------------------------------------------------------------------
          echo "***************************************************************************************************************************************************"
          echo "🌏  Injecting Logs from File: ${actFile}" 
          echo "     Quit with Ctrl-Z"
          echo "***************************************************************************************************************************************************"
          ACT_COUNT=0
          for FILE in /tmp/training-events/*; do 
              if [[ $FILE =~ "x"  ]]; then
                  ACT_COUNT=`expr $ACT_COUNT + 1`
                  echo "Injecting file ($ACT_COUNT/$(($NUM_FILES-1))) - $FILE"
                  ${KAFKACAT_EXE} -v -X security.protocol=SASL_SSL -X ssl.ca.location=./ca.crt -X sasl.mechanisms=SCRAM-SHA-512  -X sasl.username=token -X sasl.password={{ KAFKA_PASSWORD.stdout_lines[0] }} -b {{ KAFKA_BROKER.stdout_lines[0] }} -P -t {{ EVENTS_TOPIC.stdout_lines[0] }} -l $FILE                 
                  echo "      ✅ OK"
              fi
          done
          rm /tmp/training-events/x*
    done
  register: LOAD

