- name: Get password
  shell: oc get secret aiops-topology-asm-credentials -n cp4waiops -o yaml | grep password | cut -d ':' -f2 | base64 -d
  register: PASSWORD_OUTPUT
  
- name: Set password
  set_fact:
    PASSWORD: "{{ PASSWORD_OUTPUT.stdout }}"

- name: Get username
  shell: oc get secret aiops-topology-asm-credentials -n cp4waiops -o yaml | grep username | cut -d ':' -f2 | base64 -d
  register: USERNAME_OUTPUT

- name: Set username
  set_fact:
    USERNAME: "{{ USERNAME_OUTPUT.stdout }}"

- name: Get proxy domain
  shell: oc get ingress.config cluster -o jsonpath='{.spec.domain}'
  register: PROXY_DOMAIN_OUTPUT

- name: Set proxy domain
  set_fact:
    PROXY_DOMAIN: "{{ PROXY_DOMAIN_OUTPUT.stdout }}"

- name: Create a Kubernetes Observer localJob
  uri:
    url: https://asm-svt-"{{ WAIOPS_NAMESPACE }}"."{{ PROXY_DOMAIN }}"/1.0/rest-observer/jobs/bulk_replace
    user: USERNAME
    password: PASSWORD
    method: POST
    body: "{{ lookup('file','files/rest-observer.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255