- name: Check RobotShop
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "robot-shop"
  register: K8S_EXISTS

- name: Install RobotShop
  block:
  - name: Create robot-shop namespace
    kubernetes.core.k8s:
      src: ./files/robot-shop-ns.yaml
      state: present

  - name: Create a robot-shop Service Account ClusterRoleBinding
  kubernetes.core.k8s:
    src: ./files/robot1-cluster-role-binding.yaml
    state: present

  - name: Create another robot-shop Service Account ClusterRoleBinding
  kubernetes.core.k8s:
    src: ./files/robot2-cluster-role-binding.yaml
    state: present

  - name: Create robot-shop service account
  shell: |
    oc adm policy add-scc-to-user privileged -n robot-shop -z robot-shop
    oc adm policy add-scc-to-user privileged -n robot-shop -z default                                
  # ignore_errors: yes   

  - name: Create robot-shop application
    kubernetes.core.k8s:
      state: present
      namespace: robot-shop
      src: ./files/robot-all-in-one.yaml

  - name: Create robot-shop load generation
    kubernetes.core.k8s:
      state: present
      src: ./files/load-deployment.yaml
  when: K8S_EXISTS.resources|length == 0

- name: Check Kubetoy
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "kubetoy"
  register: K8S_EXISTS

- name: Install Kubetoy
  block:
  - name: Create kubetoy namespace
    kubernetes.core.k8s:
      src: ./files/kubetoy-ns.yaml
      state: present

  - name: Create kubetoy application
    kubernetes.core.k8s:
      state: present
      src: ./files/kubetoy_all_in_one.yaml
  when: K8S_EXISTS.resources|length == 0

