apiVersion: apps/v1
kind: Deployment
metadata:
  name: primecalc-deployment
  namespace: default
  labels:
    app: primecalc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: primecalc
  template:
    metadata:
      labels:
        app: primecalc
    spec:
      containers:
      - name: primecalc
        image: lostinbrittany/ovhcloud-k8s-autoscaling-demo_prime-numbers:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 400m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 50Mi
        command: ['sh', '-c', 'node index.js']