# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install Runbook Bastion Server
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: BASTION -            🔎 Check Runbook Bastion Server
  k8s_info:
    kind: Deployment
    name: bastion-host
    namespace: default
  register: K8S_EXISTS

# --------------------------------------------------------------------------------------------------------------------------------------
# Install Runbook Bastion Server
# --------------------------------------------------------------------------------------------------------------------------------------
- name: BASTION -            🚀 Install Runbook Bastion Server
  community.kubernetes.k8s:
    state: present
    namespace: "default"
    template: ./templates/runbook_bastion/create-bastion.yaml
  when: K8S_EXISTS.resources|length == 0
