
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Train RobotShop Logs
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Train RobotShop Logs
# --------------------------------------------------------------------------------------------------------------------------------------
- name: RSLOGS -             🚀 Check elasticdump executable
  shell: |
    if [ -x "$(command -v elasticdump)" ]; then
      echo "🟢 OK"
    else
      echo "  ❗ ERROR: elasticdump is not installed."
      echo "  ❌ Aborting..."
      exit 1
    fi
  register: elasticdump


- name: RSLOGS -             🚀 Get ES_USERNAME
  shell: |
    echo "$(oc get secret $(oc get secrets | grep ibm-elasticsearch-secret | awk '!/-min/' | awk '{print $1;}') -o jsonpath="{.data.username}"| base64 --decode)"
  register: ES_USERNAME


- name: RSLOGS -             🚀 Get ES_PASSWORD
  shell: |
    echo "$(oc get secret $(oc get secrets | grep ibm-elasticsearch-secret | awk '!/-min/' | awk '{print $1;}') -o jsonpath="{.data.password}"| base64 --decode)"
  register: ES_PASSWORD


- name: RSLOGS -             🚀 Get WORKING_DIR_ES
  shell: |
    echo "./ansible/training/TRAINING_FILES/ELASTIC/{{ APP_NAME }}/logs"
  register: WORKING_DIR_ES


- name: RSLOGS -             🚀 Unzip Training Data
  shell: |
    cd {{ WORKING_DIR_ES.stdout_lines[0] }}
    unzip ./data-log-training.zip
    cd -
  register: WORKING_DIR_UNZIP


- name: RSLOGS -             🚀 Check Connection
  shell: |
    existingIndexes=$(curl -s -k -u {{ ES_USERNAME.stdout_lines[0] }}:{{ ES_PASSWORD.stdout_lines[0] }} -XGET https://localhost:9200/_cat/indices)
    if [[ $existingIndexes == "" ]] ;
    then
          echo "❗ Please start port forward in separate terminal."
          echo "❗ Run the following:"
          echo "    while true; do oc port-forward statefulset/$(oc get statefulset | grep es-server-all | awk '{print $1}') 9200; done"
          echo "❌ Aborting..."
          exit 1
    fi
    echo "      ✅ OK"
  register: ES_READY



- name: RSLOGS -             🚀 Load Logs
  shell: |
    export NODE_TLS_REJECT_UNAUTHORIZED=0

    for actFile in $(ls -1 {{ WORKING_DIR_ES.stdout_lines[0] }} | grep "json"); 
    do 

          echo "    ***************************************************************************************************************************************************"
          echo "        🛠️  Uploading Index: ${actFile%".json"}" 
          echo "    ***************************************************************************************************************************************************"


          elasticdump --input="{{ WORKING_DIR_ES.stdout_lines[0] }}/${actFile}" --output=https://{{ ES_USERNAME.stdout_lines[0] }}:{{ ES_PASSWORD.stdout_lines[0] }}@localhost:9200/${actFile%".json"} --type=data --limit=1000;
          echo "   ✅  OK"
    done
  register: LOAD

