- name: Wait for Zen Ansible Script zen_ready.stdout in namespace ibm-common-services
  shell: |
    ZEN_LOGS=$(oc logs $(oc get po -n ibm-common-services|grep ibm-zen-operator|awk '{print$1}') -n ibm-common-services|grep -i "failed=0")
    echo $ZEN_LOGS
  register: zen_ready
  until: ("failed=0" in zen_ready.stdout)
  retries: 500
  delay: 15




