- name: Check Runbook Bastion Server
  kubernetes.core.k8s_info:
    kind: Deployment
    name: bastion-host
    namespace: default
  register: K8S_EXISTS

- name: Install Runbook Bastion Server
  kubernetes.core.k8s:
    state: present
    src: ./files/create-bastion.yaml
  when: K8S_EXISTS.resources|length == 0
