- name: Check Runbook Bastion Server
  k8s_info:
    kind: Deployment
    name: bastion-host
    namespace: default
  register: K8S_EXISTS

- name: Install Runbook Bastion Server
  core.kubernetes.k8s:
    state: present
    namespace: "default"
    template: ./files/create-bastion.yaml
  when: K8S_EXISTS.resources|length == 0
