---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for Watson AIOps
#
#  ©2021 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Config File
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: STORAGECLASS -       👓 Load parameters
  include_vars: ../00_config_cp4waiops.yaml


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Determine Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: STORAGECLASS -       🌏 Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


# --------------------------------------------------------------------------------------------------------------------------------------
# If Storage Classes are overridden
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ☑️  Determine Storage Class File Override
  set_fact: WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ STORAGECLASS_BLOCK_OVERRIDE }}
  when: STORAGECLASS_BLOCK_OVERRIDE!="not_configured"


- name: STORAGECLASS -       ☑️  Determine Storage Class Block Override
  set_fact: WAIOPS_STORAGE_CLASS_FILE={{ STORAGECLASS_FILE_OVERRIDE }}
  when: STORAGECLASS_FILE_OVERRIDE!="not_configured"


# --------------------------------------------------------------------------------------------------------------------------------------
# Otherwise determine Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ☑️  Determine Storage Class
  shell: |
      CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
      if [[ $CLUSTER_NAME =~ "fyre.ibm.com" ]];
      then
          echo "rook-cephfs"
      else
        if [[ $CLUSTER_NAME =~ "appdomain.cloud" ]];
        then
            echo "ibmc-file-gold-gid"
        else
          # Use Default Class (storageclass.kubernetes.io/is-default-class:true)
          SC_DEFAULT_STRING=$(oc get sc | grep "(default)")
          if [[ $SC_DEFAULT_STRING =~ "(default)" ]];
          then
            echo ${SC_DEFAULT_STRING//\(*} 
          else
            echo "No default StorageClass defined. Unable to determine what SC to use." 
            echo "Please define one using storageclass.kubernetes.io/is-default-class:true"
            echo "or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi
        fi
      fi
  register: INSTALL_DETECTED_STORAGECLASS
  when: STORAGECLASS_FILE_OVERRIDE=="not_configured" or STORAGECLASS_BLOCK_OVERRIDE=="not_configured"

# --------------------------------------------------------------------------------------------------------------------------------------
# Set File Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       💾 Set WAIOPS_STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }}
  set_fact: WAIOPS_STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
  when: STORAGECLASS_FILE_OVERRIDE=="not_configured"

# --------------------------------------------------------------------------------------------------------------------------------------
# Set Large Block Storage Class to same value
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       💾 Set WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
  set_fact: WAIOPS_STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
  when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured" 



- name: STORAGECLASS -       💿 Storage Class 
  debug: 
    msg: 
    - "** Global Storage Classes for CP4WAIOPS installation *************************************************************************"
    - " CP4WAIOPS Storage Class File:          {{WAIOPS_STORAGE_CLASS_FILE}}"
    - " CP4WAIOPS Storage Class Large Block:   {{WAIOPS_STORAGE_CLASS_LARGE_BLOCK}}"

