---
apiVersion: v1
kind: Namespace
metadata:
  name: cp4waiops-accelerator
  labels:
    name: cp4waiops-accelerator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp4waiops-accelerator
  namespace: cp4waiops-accelerator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4waiops-accelerator
subjects:
  - kind: ServiceAccount
    name: cp4waiops-accelerator
    namespace: cp4waiops-accelerator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: cp4waiops-accelerator
#   name: cp4waiops-accelerator
#   labels:
#     app: cp4waiops-accelerator
# rules:
# - apiGroups: [""]
#   resources: ["secrets", "namespaces", "deployments", "pods", "pods/exec", "services", "routes"]
#   verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: cp4waiops-accelerator
#   namespace: cp4waiops-accelerator
# subjects:
# - kind: ServiceAccount
#   name: cp4waiops-accelerator
#   namespace: cp4waiops-accelerator
# roleRef:
#   kind: Role
#   name: cp4waiops-accelerator
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cp4waiops-accelerator
#   namespace: cp4waiops-accelerator
# spec:
#   selector:
#     matchLabels:
#       app: cp4waiops-accelerator
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: cp4waiops-accelerator
#     spec:
#       containers:
#       - name: cp4waiops-accelerator
#         image: quay.io/nate_malone_ibm/cp4waiops-accelerator:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#       serviceAccount: cp4waiops-accelerator
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cp4waiops-accelerator
#   namespace: cp4waiops-accelerator
# spec:
#   selector:
#     app: cp4waiops-accelerator
#   ports:
#   - protocol: "TCP"
#     port: 8080
#     targetPort: 8080
#   type: LoadBalancer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-accelerator
  namespace: cp4waiops-accelerator
spec:
  template:
    spec:
      containers:
      - name: cp4waiops-accelerator
        image: quay.io/nate_malone_ibm/cp4waiops-accelerator:latest
        command: ["ansible-playbook",  "install-ai-manager.yaml"]
      restartPolicy: Never
  backoffLimit: 4