apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows the "demo-admin" service account 
# to have cluster-admin privileges in any namespace.
kind: ClusterRoleBinding
metadata:
  name: ibm-zen-operator-serviceaccount
subjects:
- kind: ServiceAccount
  name: ibm-zen-operator-serviceaccount
  namespace: ibm-common-services
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io