apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows the "demo-admin" service account 
# to have cluster-admin privileges in any namespace.
kind: ClusterRoleBinding
metadata:
  name: default-robotinfo2-admin
subjects:
- kind: ServiceAccount
  name: robot-shop
  namespace: default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io