- hosts: local
  vars_files: ./group_vars/ai-manager.yaml
  roles:  
# Run Prerequisites
    - role: 01_initialization
    - role: 02_rook-ceph
      when: ROOK_CEPH_INSTALL_MODE=="enable" or ROOK_CEPH_INSTALL_MODE=="automatic"
    - role: 03_aiops-get-storage-class

    - role: 04_aiops-prerequisites

# Install CP4WAIOPS Operator
    - role: 10_aiops-operator
# Install CP4WAIOPS Instance
    - role: 11_aiops-install

# Install Add-Ons while CP4WAIOPS is coming up
    - role: 20_aiops-addons-turbonomic
      when: INSTALL_TURBONOMIC

    - role: 20_2_aiops-addons-turbonomic-metrics
      when: INSTALL_TURBONOMIC_METRICS

    - role: 20_3_aiops-addons-turbonomic-gateway
      when: INSTALL_TURBONOMIC_GATEWAY

    - role: 22_aiops-addons-elk
      when: INSTALL_ELK

    - role: 23_aiops-addons-awx
      when: INSTALL_AWX

    - role: 24_aiops-addons-manageiq
      when: INSTALL_MANAGEIQ

# Install Add-Ons while CP4WAIOPS is coming up
    - role: 25_aiops-addons-ldap
      when: INSTALL_LDAP and INSTALL_AIOPS

    - role: 26_aiops-addons-user
      when: CREATE_DEMO_USER and INSTALL_AIOPS

    - role: 27_aiops-addons-demoapps
      when: INSTALL_DEMO_APPS and INSTALL_AIOPS

    - role: 28_aiops-addons-runbook-bastion
      when: INSTALL_RUNBOOK_BASTION
      
# Wait for Common Services being completely installed
    - role: 99_aiops-wait-common-services
      when: INSTALL_AIOPS

    - role: 99_aiops-wait-for-zen
      when: INSTALL_AIOPS

    - role: 30_aiops-patches
      when: INSTALL_AIOPS and INSTALL_AIOPS

# Wait for CP4WAIOPS being completely installed
    - role: 99_aiops-wait-cp4waiops
      when: INSTALL_AIOPS

    - role: 31_aiops-final-patches
      when: INSTALL_AIOPS

# Post installation tasks
    - role: 40_aiops-post-ldap-register
      when: INSTALL_LDAP and INSTALL_AIOPS


# Install Add-Ons after CP4WAIOPS has come up
    - role: install-humio
      when: INSTALL_HUMIO
 

# Get all login credentials
    - role: 90_aiops-logins
      when: PRINT_LOGINS











