#!/bin/sh

- name: Set password
  shell: oc get secret aiops-topology-asm-credentials -n cp4waiops -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}' | grep "password" | cut -d ":" -f2 | xargs
  register: PASSWORD_OUTPUT
  set_fact:
    PASSWORD: PASSWORD_OUTPUT.stdout

- name: Set username
  shell: oc get secret aiops-topology-asm-credentials -n cp4waiops -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}' | grep "username" | cut -d ":" -f2 | xargs
  register: USERNAME_OUTPUT
  set_fact:
    USERNAME: USERNAME_OUTPUT.stdout

- name: Set proxy domain
  shell: oc get ingress.config cluster -o jsonpath='{.spec.domain}'
  register: PROXY_DOMAIN_OUTPUT
  set_fact:
    PROXY_DOMAIN: PROXY_DOMAIN_OUTPUT.stdout

- name: Create a Kubernetes Observer localJob
  uri:
    url: https://asm-svt-"{{ NAMESPACE }}"."{{ PROXY_DOMAIN }}"/1.0/kubernetes-observer/jobs/local
    user: USERNAME
    password: PASSWORD
    method: POST
    body: "{{ lookup('file','cp4waiops-assets/kubernetes-observer.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255