apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: robotshop-canary-ratings
spec:
  hosts:
  - ratings.robot-shop.svc.cluster.local
  http:
  - route:
    - destination:
        host: ratings.robot-shop.svc.cluster.local
        subset: production
      weight: 50
    - destination:
        host: ratings.robot-shop.svc.cluster.local
        subset: canary
      weight: 50
